version: "3.8"  # Use a newer version

services:
  db:
    container_name: "psql-quiz-game-db"
    image: postgres:14.12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz
    ports:
      - '5432:5432'
    volumes:
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql:ro  # Moved to initdb folder
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  quiz:
    container_name: "quiz-game"
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy 
